# Generated by Django 4.1.5 on 2023-01-28 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('max_capacity', models.PositiveIntegerField(default=1)),
                ('special_info', models.CharField(max_length=100)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='own_vehicle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('driver', models.CharField(max_length=200)),
                ('require_arrival_time', models.DateTimeField(verbose_name='arrival time')),
                ('create_time', models.DateTimeField(verbose_name='order created date')),
                ('destination', models.CharField(max_length=200)),
                ('total_passengers', models.IntegerField()),
                ('allow_sharer', models.BooleanField(default=False)),
                ('sharer_capacity', models.PositiveIntegerField(default=0)),
                ('ride_type', models.CharField(choices=[('O', 'open'), ('C', 'confirmed'), ('F', 'finish')], default='O', max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
