# Generated by Django 4.1.5 on 2023-01-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharer', '0003_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('S', 'suv'), ('M', 'mininus'), ('B', 'babycar'), ('N', 'normalcar')], default='N', max_length=1),
        ),
    ]
