# Generated by Django 4.1.5 on 2023-01-29 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ridesharer', '0004_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='ride_type',
            new_name='ride_status',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='sharer_capacity',
        ),
        migrations.AddField(
            model_name='ride',
            name='require_vehicle_type',
            field=models.CharField(blank=True, choices=[('S', 'SUV'), ('M', 'MiniBus'), ('B', 'Baby Car'), ('N', 'Normal Car')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='ride',
            name='special_info',
            field=models.CharField(blank=True, max_length=200, verbose_name='special requirement'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='create_time',
            field=models.DateTimeField(verbose_name='ride created date'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='require_arrival_time',
            field=models.DateTimeField(help_text='Format: 2022-01-01 12:00', verbose_name='arrival time'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='total_passengers',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='special_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('S', 'SUV'), ('M', 'MiniBus'), ('B', 'Baby Car'), ('N', 'Normal Car')], default='N', max_length=1),
        ),
    ]
