# Generated by Django 4.1.5 on 2023-02-02 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ridesharer', '0005_rename_ride_type_ride_ride_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ride created date'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='require_arrival_time',
            field=models.DateTimeField(help_text='eg.2077-01-01 12:00', verbose_name='arrival time'),
        ),
    ]
