# Generated by Django 4.1.5 on 2023-02-04 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ridesharer', '0006_alter_ride_create_time_alter_ride_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='sharer',
            field=models.ManyToManyField(related_name='sharer_ride', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_dride', to=settings.AUTH_USER_MODEL),
        ),
    ]
