# Generated by Django 4.1.5 on 2023-02-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharer', '0007_ride_sharer_alter_ride_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('S', 'SUV'), ('M', 'MiniBus'), ('B', 'Baby Car'), ('N', 'Normal Car')], max_length=1, null=True),
        ),
    ]
