# Generated by Django 4.1.5 on 2023-02-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharer', '0009_alter_ride_require_vehicle_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='total_passengers',
            new_name='passengers',
        ),
    ]
