# Generated by Django 4.1.5 on 2023-02-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharer', '0010_rename_total_passengers_ride_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='sharer_num',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
