# Generated by Django 4.1.5 on 2023-02-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharer', '0011_ride_sharer_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='sharer_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
