# Generated by Django 4.1.5 on 2023-02-04 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharer', '0012_alter_ride_sharer_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='sharer_num',
        ),
    ]
