# Generated by Django 4.1.5 on 2023-02-06 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharer', '0015_remove_ride_sharer_shareaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareaction',
            name='shared_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_actions', to='ridesharer.ride'),
        ),
    ]
